version: '3'
services:
  platform-front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    image: ps-fr
    container_name: ps-fr
    tty: true
    volumes:
      - ./front/app:/app
      - node_modules:/app/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"

volumes:
  node_modules:
    driver: 'local'
